[project]
name = "automation-labs-pid-symbols"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "albumentations",
  "cairosvg",
  "google-cloud-storage>=3.9.0",
  "numpy",
  "opencv-python",
  "Pillow",
]
